data:
  batch_size: 128
  smiles_file: ./datasets/SelectedSMILES_QM9.txt
  type_of_encoding: 1

decoder:
  latent_dimension: 75
  gru_neurons_num: 3500
  gru_stack_size: 1

encoder:
  latent_dimension: 75
  gru_neurons_num: 3500
  gru_stack_size: 1

training:
  KLD_alpha:  0.02 #0.00005 #0.01 #0.023 #1.0e-05
  lr_enc: 0.0002427375401692564 #0.0002
  lr_dec: 0.0002427375401692564 #0.0002
  num_epochs: 5000
  sample_num: 1000