data:
  batch_size: 5000

architecture:
  hidden_dim: 512
  prop_hidden_dim: 128  
  prop_pred_activation: 'leaky_relu'
  prop_pred_dropout: 0.5
  prop_pred_depth: 1
  prop_growth_factor: 0.25

training:
  lr: 0.01
  num_epochs: 50


  
       
