data:
  batch_size: 1000

architecture:
  hidden_dim: 1000
  prop_hidden_dim: 1000  
  prop_pred_activation: 'leaky_relu'
  prop_pred_dropout: 0.4
  prop_pred_depth: 4
  prop_growth_factor: 1.0


training:
  lr: 0.001
  num_epochs: 100


  
       
