data:
 smiles_path: ./PubChemTOP_OSC.csv
 save_path: ./BF_OSC_STREN/
 tail_end: 0
 threshold: 1.3
 lower_sigma: 1
 upper_sigma: 2
 sas_threshold: 4
 z_num: 1000000

vae:
 save_path: ./3M_small/
 epoch: 10

mlp:
 save_path: ./ZS_GELU_GS/
 epoch: 25

z_mlp: 
 save_path: ./GELU_GS/
 epoch: 21

