data:
  batch_size: 64
  smiles_file: ./CSD_EES_DB_energies.csv
  save_path: ./my_save_path/
  type_of_encoding: 1

decoder:
  latent_dimension: 2048
  gru_neurons_num: 8192
  gru_stack_size: 3

encoder:
  latent_dimension: 2048
  gru_neurons_num: 8192
  gru_stack_size: 3

training:
  KLD_alpha:  0.02 #0.00005 #0.01 #0.023 #1.0e-05
  lr_enc: 0.0002427375401692564 #0.0002
  lr_dec: 0.0002427375401692564 #0.0002
  num_epochs: 1001
  sample_num: 1000