settings:
  input_dim: 64
  smiles_file: ../datasets/mystery_gen_labels.csv
  vae_file: ../extrapolation_raw/extrap_vaes/100stack_size1neurons_num2048_l_dim64num_count1/
  vae_epoch: 250
  output_folder: ./classifier_output
  num_of_cycles: 1
  selfies_alphabet: [
    "[nop]",
    "[NH1+1]",
    "[Branch2]",
    "[=Branch2]",
    "[Branch1]",
    "[#Branch2]",
    "[#C]",
    "[=NH1+1]",
    "[=C]",
    "[N-1]",
    "[NH3+1]",
    "[C-1]",
    "[=NH2+1]",
    "[Ring1]",
    "[NH2+1]",
    "[=O]",
    "[Ring2]",
    "[O]",
    "[N]",
    "[F]",
    "[=Branch1]",
    "[C]",
    "[#Branch1]",
    "[=N]",
    "[O-1]",
    "[#N]",
    "[CH1-1]"
]

hyperparameters:
  lr: 0.0001
  batch_size: 128
  hidden_dim: 64
  prop_hidden_dim: 32
  prop_pred_activation: leaky_relu
  dropout: 0
  depth: 6
  growth: 0.5
  loss_choice: 2
  learning_rate_factor: 0.1
  learning_rate_patience: 10
  epochs: 250
  weight_choice: 0.0001