vae:
  path: ./updated_vae2/stack_size1neurons_num2048_l_dim64/
  vae_epoch: 250

settings:
  batch_size: 128
  seed: 123

runs:
  end: 6
  num: 1000
  dataset: ./datasets/filtered_qm9_energies.csv
  out_path: ./extrapolation_raw/generations/saves/
  dir_name: 5
  output_folder: ./extrapolation_raw/generations/
  name: 5.txt