data:
  batch_size: 128
  smiles_file: ./datasets/filtered_qm9_energies.csv
  save_path: ./vae/
  focus_file: 1
  focus_smiles: ./datasets/filtered_qm9_energies.csv
  type_of_encoding: 1
  num_of_tests: 1
  latent_loss: 1
  full_alphabet_set: ["[#Branch1]","[=NH2+1]","[Ring1]","[F]","[NH1+1]","[=O]","[O-1]","[NH3+1]","[Branch1]","[C]","[NH2+1]","[O]","[#Branch2]","[nop]","[=Branch1]","[=C]","[=N]","[CH1-1]","[N]","[#N]","[=NH1+1]","[C-1]","[=Branch2]","[Branch2]","[#C]","[Ring2]","[N-1]"]

decoder:
  latent_dimension: 256
  gru_neurons_num: 512
  gru_stack_size: 1

encoder:
  latent_dimension: 256
  gru_neurons_num: 2048
  gru_stack_size: 1

training:
  KLD_alpha:  0.1 
  lr_enc: 0.0005 
  lr_dec: 0.0005 
  num_epochs: 251
  sample_num: 1000
