data:
  batch_size: 64
  smiles_file: ./datasets/SelectedSMILES_QM9.txt
  type_of_encoding: 1

decoder:
  latent_dimension: 50
  gru_neurons_num: 3000
  gru_stack_size: 1

encoder:
  layer_1d: 3000
  layer_2d: 1500
  layer_3d: 750
  layer_4d: 350
  layer_5d: 200
  latent_dimension: 50

training:
  KLD_alpha:  0.003210 #0.00005 #0.01 #0.023 #1.0e-05
  lr_enc: 0.002427375401692564 #0.0002
  lr_dec: 0.002427375401692564 #0.0002
  num_epochs: 5000
  sample_num: 1000