data:
 smiles_path: ./PATH/TO/SMILES/CSV
 main_dataset: ./PATH/TO/MAIN/DATASET
 save_path: ./PATH/TO/OUTPUT/FOLDER
 tail_end: 0
 mu_threshold: 2.5
 z_scale: 1.35
 lower_sigma: 1
 upper_sigma: 2
 sas_threshold: 4
 z_num: 1000000
 sanitisation_chunk_size: 10000000

vae:
 save_path: ./PATH/TO/VAE/FOLDER
 epoch: 10

mlp:
 save_path: ./PATH/TO/MLP_MU/FOLDER
 epoch: 100

z_mlp: 
 save_path: ./PATH/TO/MLP_Z/FOLDER
 epoch: 130

network_B:
  save_dir: ./PATH/TO/MLP_B/FOLDER
  OS: 0.05
  dE: 2.5

