data:
 smiles_path: ../../Datasets/Brute_force/Experimental_seeds.csv
 main_dataset: ../../Datasets/PubChemQC_3M/PubChemQC3M_noHe.csv
 save_path: ../Outputs/BF/2_5M_F/
 lower_sigma: 1
 upper_sigma: 2
 z_num: 100000

vae:
 save_path: ../Outputs/VAE/MODEL_2/
 epoch: 10

MLP:
  save_path: ../Outputs/MLP_B/MODEL_1/
  epoch: 60
  OS: 0.05
  dE: 2.5

