settings:
  smiles_file: ./PATH/TO/SMILES/CSV
  vae_file: ./PATH/TO/VAE/FOLDER
  vae_epoch: 10
  output_folder: ./PATH/TO/OUTPUT/FOLDER
  num_of_cycles: 1
  z: 0

model_params:
  input_dim: 64
  hidden_dim: 2048
  prop_pred_activation: gelu
  prop_pred_dropout: 0.1
  prop_pred_depth: 5
  prop_growth_factor: 0.65

hyperparameters:
  lr: 0.0005
  batch_size: 128
  loss_choice: 1
  learning_rate_factor: 0.3
  learning_rate_patience: 15
  epochs: 500
  weight_choice: 0.0
  batch_norm: 1