settings:
  smiles_file: ../../Datasets/PubChemQC_3M/PubChemQC3M_TRANS1.csv
  vae_file: ../Outputs/VAE/VAE_ENTROPY_TEST_2/ #../runs/3M_small/
  vae_epoch: 20
  output_folder: ../Outputs/MLP/Z_ENTROPY_TEST/
  num_of_cycles: 1
  z: 1

model_params:
  input_dim: 64
  hidden_dim: 2048
  prop_pred_activation: leaky_relu
  prop_pred_dropout: 0.1
  prop_pred_depth: 5
  prop_growth_factor: 0.65

hyperparameters:
  lr: 0.0005
  batch_size: 128
  loss_choice: 1
  learning_rate_factor: 0.3
  learning_rate_patience: 15
  epochs: 250
  weight_choice: 0.0
  batch_norm: 1