settings:
  input_dim: 64
  smiles_file: ../../symmetric_rnn_vae_folder/datasets/filtered_qm9_energies.csv
  target_file: ../../symmetric_rnn_vae_folder/datasets/filtered_qm9_energies.csv
  vae_file: PATH_TO_VAE
  vae_epoch: 250
  output_folder: ./eg_model2/
  num_of_cycles: 1
  torch_seed: 123


hyperparameters:
  lr: 0.00037
  batch_size: 128
  hidden_dim: 256
  prop_hidden_dim: 128
  prop_pred_activation: silu
  dropout: 0.07
  depth: 4
  growth: 0.65
  loss_choice: 3
  learning_rate_factor: 0.3
  learning_rate_patience: 15
  epochs: 251
  weight_choice: 0.0
